# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62199575c217656978d31f3a864dd78abf1e277665f021e31cbcb6498354a389ae9eed99604b20ddf830949969f095cd2fb4c9a53d3506889351d264c0013de7

test:
  secret_key_base: aed066bd4029d221164fe7832c271e06beb92f4fcfb0fb1ff9c30fbf9f556d7124512a90eb6dafcbe749cc16d1132e08d56ae2f7014cf65c00f1380c96cf43fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
